<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/** @var \TonyB\AdminPolicy\Block\Adminhtml\Auth\ForgottenPassword $block */
$user = $block->getUser();
?>

<form method="post" data-mage-init='{"form": {}, "validation": {}}'
      action="<?= $block->escapeUrl(
          $block->getUrl(
              '*/auth/resetpasswordpost',
              ['_query' => ['id' => $block->getUserId(), 'token' => $block->getResetPasswordLinkToken()]]
          )
      ) ?>" id="reset-password-form" autocomplete="off">
    <fieldset class="admin__fieldset">
        <legend class="admin__legend"><span><?= $block->escapeHtml(__('Reset a Password')) ?></span></legend><br />
        <input name="form_key" type="hidden" value="<?= $block->escapeHtmlAttr($block->getFormKey()) ?>" />
        <input id="username" name="username" type="hidden" value="<?= $block->escapeHtmlAttr($user->getUserName()) ?>" />
        <input id="firstname" name="firstname" type="hidden" value="<?= $block->escapeHtmlAttr($user->getFirstName()) ?>" />
        <input id="lastname" name="lastname" type="hidden" value="<?= $block->escapeHtmlAttr($user->getLastName()) ?>" />
        <div class="admin__field _required field-password">
            <label class="admin__field-label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
            <div class="admin__field-control">
                <input type="password" class="admin__control-text"
                       data-validate="{required:true, 'validate-admin-password-length':true,  'validate-admin-password-character':true,  'validate-admin-password-sensitive':true}"
                       name="password" id="password"
                       placeholder="new password" autocomplete="off" />
            </div>
        </div>
        <div class="admin__field _required field-confirmation">
            <label class="admin__field-label" for="confirmation"><span><?= $block->escapeHtml(__('Confirm New Password')) ?></span></label>
            <div class="admin__field-control">
                <input type="password" class="admin__control-text"
                       data-validate="{required:true, 'validate-cpassword':true}" name="confirmation" id="confirmation"
                       placeholder="confirm new password" autocomplete="off" />
            </div>
        </div>
        <div class="form-actions">
            <div class="actions">
                <button type="submit" title="<?= $block->escapeHtml(__('Reset Password')) ?>" class="action-reset action-primary"><span><?= $block->escapeHtml(__('Reset Password')) ?></span></button>
            </div>
            <div class="links">
                <a class="action-back" href="<?= $block->escapeUrl($block->getUrl('adminhtml', ['_nosecret' => true])) ?>"><?= $block->escapeHtml(__('Back to Sign in')) ?></a>
            </div>
        </div>
    </fieldset>
</form>
